import {
        AdvancedSQL,
        ComputerVision,
        DataCleaning,
        DataVisualization,
        FeatureEngineering,
        IntermediateMachineLearning,
        IntroToDeepLearning,
        IntroToMachineLearning,
        Pandas,
        Python,
        TimeSeries,
} from './assets/certificates/index.js';
import {
        BlaugranaFurniture,
        Imaginify,
        Jira,
        Moview,
        Ryder,
        Slack,
        Snapshot,
        ThreeDPortfolio,
        Docs,
        Funroad,
        MeetAI,
} from './assets/projects/index.js';

export const projectsData = [
        {
                id: 'meet-ai',
                Img: MeetAI,
                Title: 'Meet AI',
                Description:
                        'Meet.ai is a GPT-powered video meeting assistant built with cutting-edge AI tech. It automatically records, transcribes, summarizes, and answers questions about your meetings — all while running in the background. ',
                Link: 'https://meet-ai-zeta.vercel.app/',
                github: 'https://github.com/hha297/Meet.ai',
                TechStack: [
                        'Next.js 15',
                        'React 19',
                        'Tailwind CSS v4',
                        'Shadcn/ui',
                        'Stream Video',
                        'Stream Chat',
                        'Inngest',
                        'OpenAI',
                        'CodeRabbit',
                        'Polar',
                        'Neon PostgreSQL',
                        'Better Auth',
                ],

                Features: [
                        '🎥 Meeting Recording: Join and record meetings through browser, capturing high-quality audio/video.',
                        '✍️ Real-Time Transcription: Automatically transcribe your meetings using AssemblyAI.',
                        '🧠 GPT Summarization: Get concise, context-aware summaries using OpenAI GPT.',
                        '❓ Smart Q&A: Ask questions about the meeting and get intelligent answers.',
                        '📅 Meeting History: See and manage your past meetings with transcripts and summaries.',
                        '🔐 Authentication: Secure login and user sessions powered by Clerk.',
                        '⚡ Convex Backend: Lightning-fast backend with Convex for real-time sync.',
                        '🎨 Modern UI: Built with ShadcnUI and TailwindCSS for clean, responsive design.',
                        '📁 Transcript Download: Export transcripts in .txt or .pdf format.',
                        '📌 Timestamp Navigation: Jump to key points in the transcript via clickable timestamps.',
                        '🌐 Multi-meeting Support: Handle multiple meetings and store them for later reference.',
                ],
        },
        {
                id: 'funroad',
                Img: Funroad,
                Title: 'Funroad',
                Description:
                        'An e-commerce app where creators have their own storefronts, sell digital products, and get paid through Stripe Connect. It’s a solid, practical project that walks you through how modern platforms are made.',
                Link: 'https://funroad-iota.vercel.app/',
                github: 'https://github.com/hha297/Funroad',
                TechStack: ['Next.js 15', 'React.js', 'TypeScript', 'TailwindCSS', 'MongoDB', 'Payload CMS', 'Stripe'],
                Features: [
                        '🏬 Multi-tenant architecture',
                        '🌐 Vendor subdomains',
                        '🎨 Custom merchant storefronts',
                        '💳 Stripe Connect integration',
                        '💰 Automatic platform fees',
                        '⭐ Product ratings & reviews',
                        '📚 User purchase library',
                        '🧑‍💼 Role-based access control',
                        '🛠️ Admin dashboard',
                        '🧾 Merchant dashboard',
                        '🧱 Payload CMS backend',
                        '🗂️ Category & product filtering',
                        '🔍 Search functionality',
                        '🖼️ Image upload support',
                        '⚙️ Built with Next.js 15',
                        '🎨 TailwindCSS V4 styling',
                        '💅 ShadcnUI components',
                ],
        },
        {
                id: 'docs-editor',
                Img: Docs,
                Title: 'Docs Editor',
                Description:
                        'A professional-grade Google Docs clone featuring a rich text editor with real-time collaboration, inline comments, threaded discussions, customizable templates, and powerful document management. Built for teams and organizations with advanced editing tools, export options, and seamless authentication.',
                Link: 'https://docs-editor-ten.vercel.app',
                github: 'https://github.com/hha297/Docs-Editor',
                TechStack: [
                        'Next.js 15',
                        'React.js',
                        'TypeScript',
                        'TailwindCSS',
                        'Convex',
                        'TipTap Editor',
                        'Liveblocks',
                        'Clerk',
                ],
                Features: [
                        '📝 Rich Text Editor: Powerful TipTap editor supporting bold, italic, underline, code blocks, and more.',
                        '🤝 Real-time Collaboration: Work together in real-time with synced edits, cursor tracking, and conflict resolution.',
                        '💭 Comments & Mentions: Inline comments, threaded discussions, and user mentions for seamless team communication.',
                        '🔔 Notifications System: In-app notifications to stay updated on comments, mentions, and collaboration events.',
                        '📑 Document Templates: Create and reuse custom templates to speed up document creation.',
                        '📋 Copy & Paste Formatting: Preserve formatting when copying and pasting content.',
                        '↩️ Undo/Redo History: Navigate editing history with unlimited undo and redo functionality.',
                        '📊 Table Support: Insert and customize tables directly in the editor.',
                        '🖼️ Image Uploads: Upload and embed images with resizing and alignment controls.',
                        '📏 Margin Controls: Customize document margins and layout settings.',
                        '⬇️ Export: Download documents as PDF, HTML, TXT, or JSON for flexibility in sharing and storage.',
                        '👥 User Profiles: Manage user accounts with profile settings, avatars, and user information.',
                        '🏢 Organization Workspaces: Group users into organizations with isolated document workspaces.',
                        '✉️ Organization Invites: Invite members to your organization via email or link-based invites.',
                        '🔒 Authentication: Secure user authentication with Clerk for sign-up, login, and session management.',
                        '📱 Responsive Design: Optimized for desktops, tablets, and mobile devices.',
                        '🎯 Cursor Tracking: View collaborators’ cursors in real-time with user identification.',
                        '🎨 Text Formatting Tools: Full suite of formatting tools including headings, lists, blockquotes, and more.',
                        '📝 Lists & Checklists: Create ordered, unordered, and checklist-style lists.',
                        '🔗 Link Embedding: Embed and manage hyperlinks within documents.',
                        '⚛️ Next.js 15 Framework: Leveraging the latest features of Next.js 15 for performance and scalability.',
                        '🎨 Shadcn UI & Tailwind CSS: Modern, accessible UI components styled with Tailwind CSS and Shadcn UI.',
                ],
        },
        {
                id: 'jira-clone',
                Img: Jira,
                Title: 'Jira Clone',
                Description:
                        'An end-to-end fullstack Jira clone with workspaces, projects, epics, tasks, kanban boards, calendars, editing and deleting tasks, invite system, role-based access control, image uploads, analytics, authentication and more!',
                Link: 'https://jira-clone-hha2907s-projects.vercel.app',
                github: 'https://github.com/hha297/Jira-Clone',
                TechStack: ['Next.js', 'ReactJS', 'TypeScript', 'TailwindCSS', 'Appwrite', 'Hono.js'],
                Features: [
                        '🏢 Workspaces: Organize tasks and projects within dedicated workspaces, offering a collaborative environment.',
                        '📊 Projects / Epics: Create and manage projects and epics to structure your tasks and milestones effectively.',
                        '✅ Tasks: Assign, track, and manage tasks with detailed descriptions and deadlines.',
                        '📋 Kanban Board View: Visualize and organize tasks using a kanban board for easy tracking of project progress.',
                        '🗃️ Data Table View: An alternate view to manage tasks and projects in a structured table format.',
                        '📅 Calendar View: Keep track of deadlines, tasks, and project milestones with a comprehensive calendar view.',
                        '✉️ Invite System: Invite team members to workspaces or projects using invite links or unique codes.',
                        '⚙️ Workspace and Project Settings: Customize and configure workspace and project settings according to your needs.',
                        '🖼️ Image Uploads: Upload images for avatars, attachments, or any related resources.',
                        '🔌 Appwrite SDK Integration: Backend integration with Appwrite SDK for managing tasks, users, and storage.',
                        '⚛️ Next.js 14 Framework: Utilizes the latest Next.js 14 framework for optimal performance and scalability.',
                        '🎨 Shadcn UI & TailwindCSS Styling: Modern, responsive UI with Shadcn UI components and TailwindCSS styling.',
                        '🔍 Advanced Search and Filtering: Quickly find tasks, projects, and users with powerful search and filtering options.',
                        '📈 Analytics Dashboard: Gain insights into project performance, task completion, and team activity with an analytics dashboard.',
                        '👥 User Roles and Permissions: Implement role-based access control to ensure proper access levels across teams.',
                        '🔒 Authentication: Supports OAuth and email-based authentication for secure login.',
                        '📱 Responsive Design: Fully mobile-friendly design for easy use on all devices.',
                        '🚀 API using Hono.js: Fast and lightweight API integration with Hono.js for handling tasks and user management.',
                ],
        },
        {
                id: 'slack-clone',
                Img: Slack,
                Title: 'Slack Clone',
                Description:
                        'An end-to-end fullstack and real-time slack clone, all with workspaces, channels, 1:1 conversations, threads and file sharing.',
                Link: 'https://slack-hha2907s-projects.vercel.app',
                github: 'https://github.com/hha297/Slack',
                TechStack: ['ReactJS', 'TypeScript', 'NextJS', 'TailwindCSS', 'Convex'],
                Features: [
                        'Real time communication: Enables users to send and receive messages instantly, ensuring seamless and real-time communication across the platform.',
                        'Reactions to messages: Allows users to react to messages using emojis or custom reactions, providing a fun and quick way to engage with others.',
                        'Threads / Replies system: Facilitates threaded conversations, allowing users to reply to specific messages, keeping discussions organized and focused.',
                        'Edit / Delete messages: Provides users the ability to edit or delete their messages after sending, enabling them to correct mistakes or remove outdated content.',
                        'Role based access control: Implements role-based permissions, ensuring that users have the appropriate level of access to channels, messages, and other resources.',
                        'File sharing / Image attachments: Allows users to easily share files, documents, and images in chats, making it easier to exchange resources and media within the platform.',
                        'Authentication with Next auth v5: Integrates authentication with Next auth v5, supporting multiple login providers like Google, Facebook, and more, ensuring safe and reliable user sign-in.',
                        'Workspace / Channel creation: Lets users create workspaces and channels, providing them the flexibility to organize discussions around different projects or topics.',
                        'Invite system / Invite codes: Allows users to invite others to join workspaces or channels using invite links or unique invite codes, streamlining the onboarding process.',
                        'Direct messaging: Empowers users to send direct one-on-one messages, providing a private and personal communication option outside group chats.',
                        'User profiles: Lets users create and customize their profiles with avatars, personal details, and status messages, helping others know more about them.',
                ],
        },
        {
                id: 'snapshot',
                Img: Snapshot,
                Title: 'Snapshot',
                Description:
                        'A modern social app with a stunning UI with a native mobile feel, a special tech stack, an infinite scroll, and much more.',
                Link: 'https://snapshot-zeta-five.vercel.app/',
                github: 'https://github.com/hha297/Snapshot',
                TechStack: ['ReactJS', 'TypeScript', 'NextJS', 'TailwindCSS', 'Appwrite'],
                Features: [
                        'Authentication System: A robust authentication system ensuring security and user privacy.',
                        'Explore Page: Homepage for users to explore posts, with a featured section for top creators',
                        'Like and Save Functionality: Enable users to like and save posts, with dedicated pages for managing liked and saved content.',
                        'Create Post Page: Implement a user-friendly create post page with effortless file management, storage, and drag-drop features.',
                        'Edit Post Functionality: Provide users with the ability to edit the content of their posts at any time.',
                        'Detailed Post Page: A detailed post page displaying content and related posts for an immersive user experience.',
                        'Profile Page: A user profile page showcasing liked posts and providing options to edit the profile.',
                        "Browse Other Users: Allow users to browse and explore other user's profiles and posts.",
                ],
        },
        {
                id: 'imaginify',
                Img: Imaginify,
                Title: 'Imaginify',
                Description:
                        'An AI image SaaS platform that excels in image processing capabilities, integrates a secure payment infrastructure, offers advanced image search functionalities, and supports multiple AI features, including image restoration, recoloring, object removal, generative filling, and background removal.',
                Link: 'https://imaginify-self-eight.vercel.app/',
                github: 'https://github.com/hha297/Imaginify',
                TechStack: [
                        'ReactJS',
                        'TypeScript',
                        'NextJS',
                        'TailwindCSS',
                        'Clerk',
                        'Cloudinary',
                        'Stripe',
                        'Shadcn UI',
                ],
                Features: [
                        'Authentication and Authorization: Secure user access with registration, login, and route protection.',
                        'Community Image Showcase: Explore user transformations with easy navigation using pagination.',
                        'Advanced Image Search: Find images by content or objects present inside the image quickly and accurately.',
                        'Image Restoration: Revive old or damaged images effortlessly.',
                        'Image Recoloring: Customize images by replacing objects with desired colors easily.',
                        'Image Generative Fill: Fill in missing areas of images seamlessly.',
                        'Object Removal: Clean up images by removing unwanted objects with precision.',
                        'Background Removal: Extract objects from backgrounds with ease.',
                        'Download Transformed Images: Save and share AI-transformed images conveniently.',
                        'Transformed Image Details: View details of transformations for each image.',
                        'Transformation Management: Control over deletion and updates of transformations.',
                        'Credits System: Earn or purchase credits for image transformations.',
                        'Credits Purchase: Securely buy credits via Stripe for uninterrupted use of the service.',
                        'Profile Page: Access transformed images and credit information personally.',
                        'Responsive UI/UX: A seamless experience across devices with a user-friendly interface.',
                ],
        },
        {
                id: 'moview',
                Img: Moview,
                Title: 'Moview',
                Description:
                        'Web application that enables users to explore a diverse range of films, from blockbusters to hidden gems, and provides a platform for movie enthusiasts to discover new titles and connect with their favorite actors and actresses.',

                Link: 'https://reactjs-movie-hha2907.vercel.app/',
                github: 'https://github.com/hha297/reactjs-movie',
                TechStack: ['Javascript', 'ReactJS', 'MongoDB', 'TailwindCSS', 'NodeJS'],
                Features: [
                        'Movie Search and Filtering: Allow users to search for movies by title, genre, or release year. Provide filters to narrow down the results based on various criteria (e.g., rating, popularity, release date).',
                        'User Reviews and Ratings: Enable users to leave reviews and rate movies they’ve watched, helping other users discover movies based on real feedback.',
                        'Actor and Director Profiles: Provide detailed profiles of actors and directors, showcasing their works and allowing users to explore movies related to them.',
                        'Trending Movies: Display a list of currently trending or popular movies based on global or regional views.',
                        'Movie Trailers: Provide movie trailers directly within the app for users to watch before deciding to view the movie.',
                        'Movie Details Page: Show detailed information about each movie, such as cast, crew, ratings, and release info, along with related movies.',
                ],
        },
        {
                id: '3d-portfolio',
                Img: ThreeDPortfolio,
                Title: '3D Portfolio',
                Description:
                        'Portfolio app to showcase my projects and skills. It was developed with React, Three.js, and TailwindCSS for handling the user interface. It features a dynamic 3D scene, interactive navigation, and responsive design for an immersive user experience.',
                Link: 'https://portfolio-hha2907s-projects.vercel.app/',
                github: 'https://github.com/hha297/Portfolio',
                TechStack: ['Javascript', 'ReactJS', 'ThreeJS', 'TailwindCSS', 'Vite', 'EmailJS'],
                Features: [
                        'Customizable 3D Hero Section: Includes a 3D desktop model easily customizable to suit specific needs.',
                        'Interactive Experience and Work Sections: Utilizes animations powered by framer motion for engaging user experience.',
                        '3D Skills Section: Showcases skills using 3D geometries through three.js and React Three fiber.',
                        'Animated Projects and Testimonials: Features animated sections using framer motion for projects and client testimonials.',
                        'Contact Section with 3D Earth Model:Integrates a 3D earth model with email functionality powered by emailjs.',
                        '3D Stars: Generate stars progressively at random positions using Three.js for background display.',
                        'Consistent Animations: Implements cohesive animations throughout the website using framer motion.',
                        'Responsive Design: Ensures optimal display and functionality across all devices.',
                ],
        },
        {
                id: 'blaugrana-furniture',
                Img: BlaugranaFurniture,
                Title: 'Blaugrana Furniture',
                Description:
                        'Blaugrana Furniture app caters to individuals seeking premium furniture to elevate the style and comfort of their homes. It also serves as a dynamic platform for merchants, allowing them to showcase their exquisite furniture collections online, expand their reach, and provide customers with the convenience of browsing and ordering their products effortlessly.',
                Link: 'https://github.com/hha297/Blaugrana_Furniture',
                github: 'https://github.com/hha297/Blaugrana_Furniture',
                TechStack: ['Kotlin', 'Java', 'Coroutines', 'MVVM & LiveData', 'Firebase'],
                Features: [
                        'Browse Premium Furniture: Explore a wide variety of high-quality furniture collections for living rooms, bedrooms, and more, with detailed descriptions and images.',
                        'Merchant Dashboard: A dedicated platform for merchants to upload, manage, and showcase their furniture products, expanding their online presence.',
                        'Seamless Shopping Experience: Easily add furniture to the cart, view product details, and make secure payments through integrated payment gateways.',
                        'Order Tracking: Users can track the status of their orders in real-time, ensuring transparency and up-to-date information on delivery.',
                        'Push Notifications: Get notified about new arrivals, exclusive discounts, and special promotions for a personalized shopping experience.',
                        'Product Reviews & Ratings: Customers can leave reviews and rate products, helping others make informed purchasing decisions.',
                        'User Profiles & Favorites: Users can create personal profiles, save their favorite furniture items, and track their purchase history for a more customized experience.',
                ],
        },
        {
                id: 'ryder',
                Img: Ryder,
                Title: 'Ryder',
                Description:
                        'A fullstack mobile app with React Native for handling the user interface, Google Maps for rendering maps with directions, stripe for handling payments, serverless Postgres for managing databases, and styled with TailwindCSS, ',
                Link: 'https://github.com/hha297/Ryder',
                github: 'https://github.com/hha297/Ryder',
                TechStack: ['React Native', 'Expo', 'Stripe', 'PostgreSQL', 'Zustand', 'Clerk', 'TailwindCSS'],
                Features: [
                        'Onboarding Flow: Seamless user registration and setup process.',
                        'Email Password Authentication with Verification: Secure login with email verification.',
                        'oAuth Using Google: Easy login using Google credentials.',
                        'Authorization: Secure access control for different user roles.',
                        'Home Screen with Live Location & Google Map: Real-time location tracking with markers on a map.',
                        'Recent Rides: View a list of recent rides at a glance',
                        "Find Rides: Search for rides by entering 'From' and 'To' locations.",
                        'Select Rides from Map: Choose available cars near your location from the map.',
                        'Payment Integration: Secure payment processing using Stripe.',
                        'Create Rides After Successful Payment: Book a ride after confirming payment.',
                        'Profile: Manage account details in the profile screen.',
                        'History: Review all rides booked so far.',
                        'Responsive on Android and iOS: Optimized for both Android and iOS devices.',
                ],
        },
];
export const certificatesData = [
        { Img: AdvancedSQL },
        { Img: ComputerVision },
        { Img: DataCleaning },
        { Img: DataVisualization },
        { Img: FeatureEngineering },
        { Img: IntermediateMachineLearning },
        { Img: IntroToDeepLearning },
        { Img: IntroToMachineLearning },
        { Img: Pandas },
        { Img: Python },
        { Img: TimeSeries },
];
